spring.application.name=api-gateway
server.port=8085

# JWT secret must be provided through environment or .env file
jwt.secret-key=${JWT_SECRET}

# Downstream user service endpoint
user.service.url=http://localhost:8080

spring.cloud.gateway.routes[0].id=user-auth
spring.cloud.gateway.routes[0].uri=${user.service.url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v0/auth/**

spring.cloud.gateway.routes[1].id=test-service
spring.cloud.gateway.routes[1].uri=${user.service.url}
spring.cloud.gateway.routes[1].predicates[0]=Path=/test

spring.cloud.gateway.routes[2].id=admin-service
spring.cloud.gateway.routes[2].uri=${user.service.url}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v0/admin/**

spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=${user.service.url}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v0/**
