spring.application.name=server

server.port=8888

spring.profiles.active=native

spring.cloud.config.server.native.search-locations=file:///C:/Users/a8369/minnie/spring-config-repo
spring.security.user.name=admin
spring.security.user.password=admin

logging.level.org.springframework.cloud.config.server=DEBUG

spring.config.import=optional:file:.env[.properties]